module.exports = {
  apps: [
    {
      name: 'ruang',
      cwd: 'C:\\Users\\ASUS\\FanraAi\\ruang',
      script: 'C:\\Users\\ASUS\\FanraAi\\ruang\\node_modules\\vite\\bin\\vite.js',
      args: '--port 5173 --host',
      interpreter: 'C:\\Users\\ASUS\\AppData\\Local\\hermes\\tools\\node-26.7.0-win32-x64\\node.exe',
      interpreter_args: '--max-old-space-size=4096',
      env: { PORT: '5173' },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\ruang-error.log',
      out_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\ruang-out.log',
      log_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\ruang-combined.log',
      time: true,
      windowsHide: true,
    },
    {
      name: 'touchpad',
      cwd: 'C:\\Users\\ASUS\\FanraAi\\remote-touchpad',
      script: 'C:\\Program Files\\Python314\\python.exe',
      args: 'server.py',
      env: { PORT: '8000' },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\touchpad-error.log',
      out_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\touchpad-out.log',
      log_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\touchpad-combined.log',
      time: true,
      windowsHide: true,
    },
    {
      name: 'auto-clean',
      cwd: 'C:\\Users\\ASUS\\FanraAi',
      script: 'C:\\Program Files\\Python314\\pythonw.exe',
      args: 'auto-clean.py',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\auto-clean-error.log',
      out_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\auto-clean-out.log',
      time: true,
      windowsHide: true,
    },
    {
      name: 'sync-tunnels',
      cwd: 'C:\\Users\\ASUS\\FanraAi',
      script: 'C:\\Program Files\\Python314\\pythonw.exe',
      args: 'sync-tunnels.py',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\sync-tunnels-error.log',
      out_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\sync-tunnels-out.log',
      time: true,
      windowsHide: true,
    },
    {
      name: 'touchpad-dashboard',
      cwd: 'C:\\Users\\ASUS\\FanraAi\\touchpad-dashboard',
      script: 'C:\\Users\\ASUS\\FanraAi\\touchpad-dashboard\\node_modules\\next\\dist\\bin\\next',
      args: 'dev -p 3000',
      interpreter: 'C:\\Users\\ASUS\\AppData\\Local\\hermes\\tools\\node-26.7.0-win32-x64\\node.exe',
      interpreter_args: '--max-old-space-size=4096',
      env: {
        PORT: '3000',
        // WSS publik untuk akses touchpad dari luar (Cloudflare Tunnel ke :8000)
        NEXT_PUBLIC_TOUCHPAD_WS: 'wss://lucas-norman-ipod-need.trycloudflare.com/ws',
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\dashboard-error.log',
      out_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\dashboard-out.log',
      log_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\dashboard-combined.log',
      time: true,
      windowsHide: true,
    },
  ],
}