module.exports = {
  apps: [
    {
      name: 'ruang',
      cwd: 'C:/Users/ASUS/FanraAi/ruang/build/server',
      script: 'index.js',
      args: '',
      interpreter: 'C:/Users/ASUS/AppData/Local/hermes/tools/node-26.7.0-win32-x64/node.exe',
      interpreter_args: '--max-old-space-size=4096',
      env: { PORT: '3001', RUANG_PORT: '3001' },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'C:/Users/ASUS/FanraAi/logs/ruang-error.log',
      out_file: 'C:/Users/ASUS/FanraAi/logs/ruang-out.log',
      log_file: 'C:/Users/ASUS/FanraAi/logs/ruang-combined.log',
      time: true,
      windowsHide: true,
    },
    {
      name: 'touchpad',
      cwd: 'C:\\Users\\ASUS\\FanraAi\\remote-touchpad',
      script: 'C:\\Program Files\\Python314\\python.exe',
      args: 'server.py',
      env: { PORT: '8000' },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\touchpad-error.log',
      out_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\touchpad-out.log',
      log_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\touchpad-combined.log',
      time: true,
      windowsHide: true,
    },
    {
      name: 'auto-clean',
      cwd: 'C:\\Users\\ASUS\\FanraAi',
      script: 'C:\\Program Files\\Python314\\pythonw.exe',
      args: 'auto-clean.py',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\auto-clean-error.log',
      out_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\auto-clean-out.log',
      time: true,
      windowsHide: true,
    },
    {
      name: 'sync-tunnels',
      cwd: 'C:\\Users\\ASUS\\FanraAi',
      script: 'C:\\Program Files\\Python314\\pythonw.exe',
      args: 'sync-tunnels.py',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\sync-tunnels-error.log',
      out_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\sync-tunnels-out.log',
      time: true,
      windowsHide: true,
    },
    {
      name: 'multi-agents',
      cwd: 'C:\\Users\\ASUS\\FanraAi',
      script: 'C:\\Program Files\\Python314\\python.exe',
      args: '-u agents/multi_agents.py',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\agents-error.log',
      out_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\agents-out.log',
      log_file: 'C:\\Users\\ASUS\\FanraAi\\logs\\agents-combined.log',
      time: true,
      windowsHide: true,
    },
  ],
}